name = "action"
version = "1.0.0"
description = "A Gleam web application"

[dependencies]
gleam_stdlib = "~> 0.29"
mist = "~> 0.12"
nakai = "~> 0.8"
framework = { path = "../framework" }

[dev-dependencies]
gleeunit = "~> 0.10"
