name = "tiny_database"
version = "1.0.0"
description = "A silly little database to be used in the examples"
licences = ["Apache-2.0"]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.30"
simplifile = "~> 1.0"
gleam_json = "~> 0.6"
youid = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
