name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./action
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "25.2"
          gleam-version: "0.30.0"
          rebar3-version: "3"
          # elixir-version: "1.14.2"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
